---
name: Docker
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  schedule:
    - cron: '42 4 * * *'

env:
  GOPATH: /home/runner/go
  GOCACHE: /home/runner/go/cache
  GOMODCACHE: /home/runner/go/cache/mod
  GOPROXY: https://proxy.golang.org # remove direct

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request_target' || contains(github.event.pull_request.labels.*.name, 'trust')

    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Checkout code
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout pull request code
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Go
        uses: FerretDB/github-actions/setup-go@main
        with:
          cache-key: build

      - name: Initialize Docker Buildx builder
        run: make docker-init

      - name: Extract Docker image name and tag
        id: extract-docker-tag
        uses: FerretDB/github-actions/extract-docker-tag@main

      - name: Build Docker image ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
        run: make docker-push
        env:
          DOCKER_IMAGE: ${{ steps.extract-docker-tag.outputs.image }}
          DOCKER_TAG: ${{ steps.extract-docker-tag.outputs.tag }}

      - name: Check dirty
        run: |
          git status
          git diff --exit-code
