---
name: docker_push_oci_image

on:
  workflow_run:
    workflows: ["docker_build_oci_image"]

env:
  GOPATH: /home/runner/go
  GOCACHE: /home/runner/go/cache
  GOMODCACHE: /home/runner/go/cache/mod
  GOPROXY: https://proxy.golang.org # remove direct

jobs:
  docker_push_oci_image:
    name: docker_push_oci_image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          use: false # we initialize our own instance below

      - name: Setup Go
        uses: FerretDB/github-actions/setup-go@main
        with:
          cache-key: test

      - name: Initialize builder instance
        run: make docker-init

      - name: Extract Docker image tag
        id: extract-docker-tag
        uses: FerretDB/github-actions/extract-docker-tag@main

      - name: Download OCI image
        uses: actions/download-artifact@v2
        with:
          name: dev-ferretdb-${{ steps.extract-docker-tag.outputs.tag }}.tar

      - name: Import OCI
        run: make import OCI

      - name: Push image
        run: make docker-push
