---
name: Go Cron
on:
  schedule:
    - cron: "12 0 * * *"

env:
  GOPATH: /home/runner/go
  GOCACHE: /home/runner/go/cache
  GOLANGCI_LINT_CACHE: /home/runner/go/cache/lint
  GOMODCACHE: /home/runner/go/mod
  GOPROXY: https://proxy.golang.org
  GOTOOLCHAIN: local

jobs:
  integration:
    name: Integration

    # To avoid conflict with go.yml.
    concurrency:
      group: ${{ github.workflow }}-integration-${{ matrix.name }}-${{ matrix.shard_index }}-${{ matrix.disable_filter_pushdown || false }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "SQLite", task: "sqlite", shard_index: 1, shard_total: 3, disable_filter_pushdown: true }
          - { name: "SQLite", task: "sqlite", shard_index: 2, shard_total: 3, disable_filter_pushdown: true }
          - { name: "SQLite", task: "sqlite", shard_index: 3, shard_total: 3, disable_filter_pushdown: true }

    uses: ./.github/workflows/call-test-integration.yml
    with:
      name: ${{ matrix.name }}
      task: ${{ matrix.task }}
      shard_index: ${{ matrix.shard_index }}
      shard_total: ${{ matrix.shard_total }}
      disable_filter_pushdown: ${{ matrix.disable_filter_pushdown || false }}
